### ISSUE TITLE
Tuner gives unusable results

### ISSUE THREAD

**Issue by ghost** [Mk-Chan/libchess#16]
Please see pastebins I posted in irc

**Comment by Mk-Chan** [comment]
Can you please post them here, it'll be easier to find when I get to working on it

**Comment by ghost** [comment]
micah revision 55d8aed9250ba6c89d6a3e828bf34295cb7bf4da

# error: 0.079083754255436151 (28.121834%), took: 401.934000s
tune_bishop_count=44
tune_too_many_pawns=11
tune_zero_pawns=-10
tune_isolated_pawns=-16
tune_rook_on_open_file=26
tune_double_pawns=11
tune_bishop_open_diagonal=126
tune_pawn=97
tune_knight=394
tune_bishop=395
tune_rook=643
tune_queen=1283
tune_king_shield=4
tune_psq_mul=205
tune_psq_div=301
tune_pp_scores_mg_1=0
tune_pp_scores_mg_2=-1
tune_pp_scores_mg_3=14
tune_pp_scores_mg_4=29
tune_pp_scores_mg_5=84
tune_pp_scores_mg_6=143
tune_pp_scores_eg_1=-185
tune_pp_scores_eg_2=-230
tune_pp_scores_eg_3=-78
tune_pp_scores_eg_4=138
tune_pp_scores_eg_5=-210
tune_pp_scores_eg_6=-291
#---

**Comment by ghost** [comment]
f9ba25e3202a9d3de47f352b4a974f411eed6a49

# error: 0.078786445070135741 (28.068923%), took: 364.391000s
tune_bishop_count=43
tune_too_many_pawns=24
tune_zero_pawns=0
tune_isolated_pawns=-25
tune_rook_on_open_file=27
tune_double_pawns=7
tune_bishop_open_diagonal=319
tune_pawn=100
tune_knight=439
tune_bishop=442
tune_rook=711
tune_queen=1412
tune_king_shield=5
tune_psq_mul=114
tune_psq_div=150
tune_pp_scores_mg_1=-3
tune_pp_scores_mg_2=-4
tune_pp_scores_mg_3=20
tune_pp_scores_mg_4=40
tune_pp_scores_mg_5=84
tune_pp_scores_mg_6=151
tune_pp_scores_eg_1=-243
tune_pp_scores_eg_2=-27
tune_pp_scores_eg_3=52
tune_pp_scores_eg_4=-546
tune_pp_scores_eg_5=-391
tune_pp_scores_eg_6=170
#---

**Comment by ghost** [comment]
Note that these two examples were with 0 as starting-point; adjust eval_par.h for that.

**Comment by Mk-Chan** [comment]
Passed pawn results are likely due to the training set since the error is lower without the passed pawn eval.
