### ISSUE TITLE
UCI as a configuration and service

### ISSUE THREAD

**Issue by Mk-Chan** [Mk-Chan/libchess#5]
A uci.h file which engines can configure with available features and hooks to trigger output such as `info cp 100 time 1300....` and `option name Threads ....`.

**Comment by ghost** [comment]
oh and xboard protocol

**Comment by Mk-Chan** [comment]
In progress here: #13

**Comment by Mk-Chan** [comment]
Completed with https://github.com/Mk-Chan/libchess/commit/fb02e61885c14f605eb68e5336844190e433121e
